package vssss

import (
	_ "embed"
)

// SignalsDB is the embedded SQLite database containing VSS signals and their embeddings.
// This file is generated by cmd/generate and embedded at compile time.
//
//go:embed signals.db
var SignalsDB []byte
