// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Signal struct {
	ID          int64  `json:"id"`
	Path        string `json:"path"`
	Description string `json:"description"`
	Type        string `json:"type"`
	Datatype    string `json:"datatype"`
	Unit        string `json:"unit"`
}
