// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"strings"
)

const countSignals = `-- name: CountSignals :one
SELECT COUNT(*) FROM signals
`

func (q *Queries) CountSignals(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSignals)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSignalByID = `-- name: GetSignalByID :one
SELECT id, path, description, type, datatype, unit
FROM signals
WHERE id = ?
`

func (q *Queries) GetSignalByID(ctx context.Context, id int64) (Signal, error) {
	row := q.db.QueryRowContext(ctx, getSignalByID, id)
	var i Signal
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Description,
		&i.Type,
		&i.Datatype,
		&i.Unit,
	)
	return i, err
}

const getSignalByPath = `-- name: GetSignalByPath :one
SELECT id, path, description, type, datatype, unit
FROM signals
WHERE path = ?
`

func (q *Queries) GetSignalByPath(ctx context.Context, path string) (Signal, error) {
	row := q.db.QueryRowContext(ctx, getSignalByPath, path)
	var i Signal
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Description,
		&i.Type,
		&i.Datatype,
		&i.Unit,
	)
	return i, err
}

const getSignalsByIDs = `-- name: GetSignalsByIDs :many
SELECT id, path, description, type, datatype, unit
FROM signals
WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) GetSignalsByIDs(ctx context.Context, ids []int64) ([]Signal, error) {
	query := getSignalsByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Signal{}
	for rows.Next() {
		var i Signal
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Description,
			&i.Type,
			&i.Datatype,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSignal = `-- name: InsertSignal :one
INSERT INTO signals (path, description, type, datatype, unit)
VALUES (?, ?, ?, ?, ?)
RETURNING id
`

type InsertSignalParams struct {
	Path        string `json:"path"`
	Description string `json:"description"`
	Type        string `json:"type"`
	Datatype    string `json:"datatype"`
	Unit        string `json:"unit"`
}

func (q *Queries) InsertSignal(ctx context.Context, arg InsertSignalParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertSignal,
		arg.Path,
		arg.Description,
		arg.Type,
		arg.Datatype,
		arg.Unit,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
